### ISSUE TITLE
Scala 2.13

### ISSUE THREAD

**Issue by jamesward** [ocadaruma/scalikejdbc-bigquery#46]
Looks like Scala 2.13 support is in the repo but not yet released. Would be awesome to have a 2.13 compatible release.  Thanks!

**Comment by ocadaruma** [comment]
Oh, please wait for a while.

**Comment by ocadaruma** [comment]
@jamesward Thank you for your waiting.
scalikejdbc-bigquery 0.1.4 which includes scala 2.13 support is now available.

**Comment by takayahilton** [comment]
Can close?

**Comment by jamesward** [comment]
Yup, thanks!
